//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CounsellingEntities : DbContext
    {
        public CounsellingEntities()
            : base("name=CounsellingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<appointment> appointments { get; set; }
        public DbSet<counselor> counselors { get; set; }
        public DbSet<loginauthentication> loginauthentications { get; set; }
        public DbSet<scheduledappointment> scheduledappointments { get; set; }
        public DbSet<Student> Students { get; set; }
    }
}
