//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class counselor
    {
        public counselor()
        {
            this.appointments = new HashSet<appointment>();
        }
    
        public int CounselorID { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<appointment> appointments { get; set; }
    }
}
